model_name: "baseline_model"
mode: "holdout"
use_holdout: False
logger:
  project: "graph-nets-eval"
  entity: "scaling-graph-nets"
paths:
  data: "data"
  raw_data: "data"
  vocab: "vocab.txt"
  holdout_losses: "data/holdout_losses.npy"
model:
  configuration: "gatv2conv"
  base:
    hidden_dim: 32
    dropout_rate: 0.1
    num_edge_types: 13
    edge_attr_dim: 8
  gatv2conv:
    num_layers: 4
    typed_edges: True
data:
  batch_size: 128 # In samples
  max_sequence_length: 512
  drop_sequence_length: 512
  max_token_length: 8  # In terms of (BPE) sub-tokens.
training:
  max_steps: 100
  print_freq: 1000
  learning_rate: 0.0001
trainer:
  accelerator: "gpu"
  devices:
    - 3
  max_epochs: 2
  val_check_interval: 1.
