max_batch_size: 12500
max_buffer_size: 50  # In terms of no. of (maximum efficiency) batches.
max_sequence_length: 512
valid_interval: 250000
max_valid_samples: 25000
max_token_length: 10  # In terms of (BPE) sub-tokens.
